## Numpy

`Numpy` is the main way to deal with numerical data in python. Basic python can be slow (for loops are slow for example). Numpy avoids these problems by using efficient C code behind the scenes.

Numpy was developed to be Matlab-like. As such there are many functions named the same thing. However, there are important differences. I will try to point them out here, but a good reference is this numpy guide for Matlab users: https://numpy.org/doc/stable/user/numpy-for-matlab-users.html

Also note that much of this tutorial will be a parred down version of Jake VanderPlas' excellent guide *Python Data Science Handbook*, which is available free online here: https://jakevdp.github.io/PythonDataScienceHandbook

Let's import the numpy package.

Numpy is conventionally renamed to `np` on import. This is widely used by lots of people so it is good to keep following it.

In [1]:
import numpy as np

### Arrays

The basic unit of numpy is the **numpy array**. Like a `list`, it is a container of objects. Unlike a list, it usually contains numbers and this is part of what makes it efficient to use.

We can make a numpy array from a list of numbers as follows:

In [2]:
a = np.asarray([10, 20, 30])
a

array([10, 20, 30])

Arrays have several important properties:
+ `size` is the number of elements in the array.
+ `ndim` is the number of dimensions of the array
+ `shape` is the number of elements in each dimension
+ `dtype` is the type of element in the array. Here are the most common types:
    + `int64`: 64-bit integers
    + `float64`: double precision floating point numbers
    + `bool`: boolean

In [3]:
a.size

3

In [4]:
a.ndim

1

In [5]:
a.shape

(3,)

In [6]:
a.dtype

dtype('int64')

We can also look at the size of the array in memory using the `nbytes` property

In [7]:
f'{a.nbytes} bytes'

'24 bytes'

Let's make a multidimensional array and compare:

In [8]:
b = np.asarray([[10.0, 11.0, 12.0],
                [20.0, 21.0, 22.0],
                [30.0, 31.0, 32.0]])
b

array([[10., 11., 12.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [9]:
b.size

9

In [10]:
b.ndim

2

In [11]:
b.shape

(3, 3)

In [12]:
b.dtype

dtype('float64')

In [13]:
f'{b.nbytes} bytes'

'72 bytes'

We can see that this array has two dimensions with three elements each. The array takes up more space in memory because it has more elements and because it is of type `float64` (floating point numbers take up more space than integers).

### Indexing into numpy arrays

Indexing into numpy arrays is very similar to indexing into lists, except we have to deal with the dimensions of the array.

In [14]:
b

array([[10., 11., 12.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [15]:
b[0, 0]

10.0

In [16]:
b[1, 0]

20.0

In [17]:
b[2, 0]

30.0

In [18]:
b[0, 1]

11.0

In [19]:
b[0, 2]

12.0

Like in lists, we can use the colons to give us several elements of a dimension using `array[start:stop:step]`

We can also omit start, stop, and step for convenience. For example:

In [20]:
b[0, 0:3:1]

array([10., 11., 12.])

This is the same as:

In [21]:
b[0, :]

array([10., 11., 12.])

We can do it for the other dimensions as well:

In [22]:
b[:, 0]

array([10., 20., 30.])

In [23]:
b[:, 1]

array([11., 21., 31.])

You can omit the colon if it's the first dimension

In [24]:
b[0]

array([10., 11., 12.])

In [25]:
b[0, :]

array([10., 11., 12.])

You can also reverse elements of the array like in lists using step

In [26]:
b[0]

array([10., 11., 12.])

In [27]:
b[0, ::-1]

array([12., 11., 10.])

You can also index into two dimensions at once

In [28]:
b

array([[10., 11., 12.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [29]:
b[::2, ::2]

array([[10., 12.],
       [30., 32.]])

In [30]:
b[:2, :2]

array([[10., 11.],
       [20., 21.]])

You can use `np.ix_` to index specific elements of each dimension in a Matlab-like way

In [31]:
b[np.ix_([0, 1], [1, 2])]

array([[11., 12.],
       [21., 22.]])

This says give me the intersection of row 0 and row 1 and column 1 and column 2. Note that `np.ix_` achieves this by outputting a tuple with the following arrays:

In [32]:
np.ix_([0, 1], [1, 2])

(array([[0],
        [1]]),
 array([[1, 2]]))

This says give me the intersection of row 0 and row 1 and column 0 and column 2

In [33]:
b[np.ix_([0, 1], [0, 2])]

array([[10., 12.],
       [20., 22.]])

In [34]:
b[np.ix_([1, 2], [0, 2])]

array([[20., 22.],
       [30., 32.]])

You can use boolean arrays to index into arrays

In [35]:
b

array([[10., 11., 12.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [36]:
is_true = np.asarray([True, False, True])

b[is_true]

array([[10., 11., 12.],
       [30., 31., 32.]])

Note that you can also use `np.ix_` with boolean arrays:

In [37]:
b[np.ix_([True, False, True], [False, True, True])]

array([[11., 12.],
       [31., 32.]])

You can use comparisons to implicitly generate boolean arrays. Notice that this flattens the array in this case.

In [38]:
b[b < 21]

array([10., 11., 12., 20.])

We can also combine comparisons. We do this using python's bitwise operators, which act on each element of the array. The parenthesis are important here:
+ `|` means **or**
+ `&` means **and**
+ `~` means **not**

In [39]:
b[(b < 21) | (b > 31)]

array([10., 11., 12., 20., 32.])

In [40]:
b[(b < 21) & ~(b > 31)]

array([10., 11., 12., 20.])

### Modifying existing arrays

Like lists, you can also modify elements of the array using indexing

In [41]:
b

array([[10., 11., 12.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [42]:
b[0, 0] = 9
b

array([[ 9., 11., 12.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [43]:
b[:, 2] = 2
b

array([[ 9., 11.,  2.],
       [20., 21.,  2.],
       [30., 31.,  2.]])

In [44]:
b[:, 2] = [1, 2, 3]
b

array([[ 9., 11.,  1.],
       [20., 21.,  2.],
       [30., 31.,  3.]])

You can add a new dimension to the array by using `np.newaxis`

In [45]:
b.shape

(3, 3)

In [46]:
b[:, :, np.newaxis].shape

(3, 3, 1)

#### Reshaping arrays

In [47]:
c = np.asarray([[0, 0, 0],
                [1, 1, 1]])
c

array([[0, 0, 0],
       [1, 1, 1]])

In [48]:
c.shape

(2, 3)

In [49]:
c.reshape((3, 2))

array([[0, 0],
       [0, 1],
       [1, 1]])

In [50]:
c.reshape((3, 2)).shape

(3, 2)

In [51]:
c.reshape((6,))

array([0, 0, 0, 1, 1, 1])

In [52]:
c.flatten()

array([0, 0, 0, 1, 1, 1])

### Joining arrays

Use the functions `np.concatenate` and `np.stack` to join arrays together.

Notice that these each take an `axis` keyword argument to specify which dimensions to combine the arrays.

In [53]:
a = np.asarray([1, 1, 1])
b = np.asarray([0, 0, 0])

In [54]:
a

array([1, 1, 1])

In [55]:
b

array([0, 0, 0])

In [56]:
a.shape

(3,)

In [57]:
b.shape

(3,)

In [58]:
c = np.concatenate((a, b), axis=0)

c

array([1, 1, 1, 0, 0, 0])

In [59]:
c.shape

(6,)

In [60]:
# np.concatenate((a, b), axis=1)

In [61]:
np.concatenate((a[:, np.newaxis], b[:, np.newaxis]), axis=1)

array([[1, 0],
       [1, 0],
       [1, 0]])

In [62]:
np.concatenate((a[:, np.newaxis], b[:, np.newaxis]), axis=1).shape

(3, 2)

`stack` is just like concatenate but it automatically adds a new axis

In [63]:
np.stack((a, b), axis=0)

array([[1, 1, 1],
       [0, 0, 0]])

In [64]:
np.stack((a, b), axis=1)

array([[1, 0],
       [1, 0],
       [1, 0]])

### Universal Functions

For Loops in python are slow. Take advantage of the C code implementations used by numpy by using array operations.

You can apply basic math functions for all elements of an array.

In [65]:
a

array([1, 1, 1])

In [66]:
np.log(a)

array([0., 0., 0.])

In [67]:
a * 3

array([3, 3, 3])

In [68]:
a - 3

array([-2, -2, -2])

In [69]:
(a + 1) ** 3

array([8, 8, 8])

There are also a number of numpy functions that can be applied universally over every element or over an individual axis of the array.

In [70]:
c = np.asarray([[0, 0, 0],
                [1, 1, 1]])
c.shape

(2, 3)

In [71]:
np.mean(c)

0.5

In [72]:
np.mean(c, axis=0)

array([0.5, 0.5, 0.5])

Note that applying over axis 0 means taking the mean on the columns.

Applying over axis 1 means taking the mean on the rows

In [73]:
np.mean(c, axis=1)

array([0., 1.])

You can also apply the mean over several axes at a time. In this case, because there are only two axes, the result is the same as taking the mean over all elements

In [74]:
np.mean(c, axis=(0, 1))

0.5

Note that some of these functions can be called directly on the arrays. You can use `dir(c)` where `c` is a numpy array to figure out which functions these are:

In [75]:
c.mean()

0.5

Some other useful functions

In [76]:
np.max(c)

1

In [77]:
np.min(c)

0

In [78]:
np.unique(c)

array([0, 1])

In [79]:
d = np.asarray([-1, 1, -2])
np.abs(d)

array([1, 1, 2])

In [80]:
np.sum(c)

3

An especially handy function on boolean arrays (like Matlab's find) is np.nonzero, which finds the index of non-zero values for each dimension.

In [81]:
boolean_array = np.asarray([True, False, True])

np.nonzero(boolean_array)

(array([0, 2]),)

### Array on Array Operations

Multiplication of two arrays (\*) is always element-wise. Pay attention to this Matlab users.

In [82]:
a

array([1, 1, 1])

In [83]:
a + a

array([2, 2, 2])

In [84]:
a * a

array([1, 1, 1])

In [85]:
a - a

array([0, 0, 0])

If you want to do matrix multiplication with arrays, you use the (`@`) symbol. As always with matrix multiplication, you have to pay attention to the dimensions.

In [86]:
a.shape

(3,)

In [87]:
a @ a

3

In [88]:
c = np.asarray([[0, 0, 0],
                [1, 1, 1]])
c.shape

(2, 3)

Uncomment this and see it fail

In [ ]:
# c @ c

In [ ]:
c @ c.T

### Array broadcasting

Numpy allows arrays of different shapes to be added, subtracted, or multiplied. Numpy will automatically duplicate the missing dimension of the smaller array to be the right size.

In [ ]:
M = np.ones((3, 3))
M

In [ ]:
a = np.array([0, 1, 2])
a

In [ ]:
M.shape

In [ ]:
a.shape

In [ ]:
a + M

In [ ]:
(a + M).shape

This is equivalent to:

In [ ]:
implicit_a = np.array([[0, 1, 2],
                       [0, 1, 2],
                       [0, 1, 2]])
implicit_a + M

The rules of broadcasting (copied from Jake VanderPlas' book):

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

+ Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
+ Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
+ Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [ ]:
M = np.ones((3, 2))
a = np.arange(3)

a, M

In [ ]:
a.shape

In [ ]:
M.shape

This won't work:

In [ ]:
# a + M

We can make it work by adding a new axis

In [ ]:
a[:, np.newaxis].shape

In [ ]:
a[:, np.newaxis] + M

In [ ]:
(a[:, np.newaxis] + M).shape